/*
 * This source file was generated by the Gradle 'init' task
 */
package solitaire;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Deque;
import java.util.HashMap;
import java.util.LinkedList;

import solitaire.utils.Card;
import solitaire.utils.CardStack;
import solitaire.utils.Foundation;
import solitaire.utils.Suit;
import solitaire.utils.Value;
import solitaire.utils.Waste;

public class App {
    public boolean wasteCardToTableu(Waste waste, Deque<Card> stock, CardStack[] tableu) {
        boolean move = false;
        if (waste.size() == 0) {
            waste.drawThree(stock);
        }

        Card top = waste.getTop();
        for (CardStack cardStack : tableu) {
            if (top.isCompatibleBelow(cardStack.getRevealedBottom())) {
                Card c = waste.popTop();

                cardStack.appendCard(c);
                move = true;
                break;
            }
        }
        return move;
    }

    public boolean wasteCardToFoundation(Waste waste, Deque<Card> stock, Foundation[] foundations) {
        boolean move = false;
        if (waste.size() == 0) {
            waste.drawThree(stock);
        }

        Card top = waste.getTop();

        for (Foundation foundation : foundations) {
            if (foundation.pushable(top)) {
                Card c = waste.popTop();
                foundation.push(c);
                move = true;
                break;
            }
        }

        return move;
    }

    public boolean wasteAceToFoundation(Waste waste, Deque<Card> stock, Foundation[] foundations) {
        boolean move = false;
        if (waste.size() == 0) {
            waste.drawThree(stock);
        }

        Card top = waste.getTop();
        if (top.value() != Value.ACE) {
            return false;
        }

        for (Foundation foundation : foundations) {
            if (!foundation.empty()) {
                continue;
            }

            Card c = waste.popTop();
            foundation.push(c);
            move = true;
            break;
        }

        return move;
    }

    public boolean wasteKingToTableu(Waste waste, Deque<Card> stock, CardStack[] tableu) {
        boolean move = false;
        if (waste.size() == 0) {
            waste.drawThree(stock);
        }

        Card top = waste.getTop();
        if (top.value() != Value.KING) {
            return false;
        }

        for (CardStack cardStack : tableu) {
            if (cardStack.empty()) {
                cardStack.pushCard(waste.popTop());
                move = true;
                break;
            }
        }

        return move;
    }

    public boolean cardsToFoundation(CardStack[] tableu, Foundation[] foundations) {
        boolean move = false;

        for (CardStack stack : tableu) {
            if (stack.empty()) {
                continue;
            }

            boolean pushable = true;
            while (!stack.empty() && pushable) {
                for (Foundation foundation : foundations) {
                    Card end = stack.getRevealedBottom();
                    if (!foundation.pushable(end)) {
                        pushable = false;
                        continue;
                    }

                    foundation.push(stack.popCard());
                    move = true;
                    pushable = true;
                    break;
                }
            }
        }

        return move;
    }

    public boolean aceToFoundations(CardStack[] tableu, Foundation[] foundations) {
        boolean move = false;
        for (CardStack stack : tableu) {
            if (stack.empty()) {
                continue;
            }
            Card end = stack.getRevealedBottom();
            if (end.value() != Value.ACE) {
                continue;
            }

            for (Foundation foundation : foundations) {
                if (!foundation.empty()) {
                    continue;
                }

                Card c = stack.popCard();
                foundation.push(c);
                move = true;
                break;
            }
        }

        return move;
    }

    public boolean kingToEmpty(CardStack[] tableu) {
        ArrayList<Integer> emptyStackIndexes = new ArrayList<>();
        boolean move = false;

        for (int i = 0; i < tableu.length; i++) {
            if (tableu[i].empty()) {
                emptyStackIndexes.add(i);
            }
        }

        if(emptyStackIndexes.isEmpty()) {
            return move;
        }

        int nextMarkedStack = 0;

        for (CardStack stack : tableu) {
            if (stack.empty()) {
                continue;
            }

            if (stack.revealedStart() > 0 && stack.getRevealedTop().value() == Value.KING) {
                CardStack kingStack = stack.splitStack(stack.revealedStart()).get();
                tableu[emptyStackIndexes.get(nextMarkedStack)].mergeStacks(kingStack);
                nextMarkedStack += 1;
                move = true;
            }
        }

        return move;
    }

    public boolean lateralMoves(CardStack[] tableu) {
        boolean move = false;

        // CardStack A - to move
        // CardStack B - to receive
        for (CardStack stackToMove : tableu) {
            if (stackToMove.empty()) {
                continue;
            }
            if (stackToMove.revealedStart() == 0 && stackToMove.getRevealedTop().value() == Value.KING) {
                continue;
            }
            for (CardStack stackToReceive : tableu) {
                if (stackToMove == stackToReceive) {
                    continue;
                }

                if (stackToReceive.empty() && stackToMove.getRevealedTop().value() != Value.KING) {
                    continue;
                }

                if(stackToMove.getRevealedTop().isCompatibleBelow(stackToReceive.getRevealedBottom())) {
                    var temp = stackToMove.splitStack(stackToMove.revealedStart());

                    if(temp.isEmpty()) {
                        continue;
                    }

                    CardStack cs = temp.get();

                    stackToReceive.mergeStacks(cs);
                    move = true;
                    break;
                }
            }
        }

        return move;
    }

    public boolean buildTableu(CardStack[] tableu, Foundation[] foundations) {
        boolean move = false;
        move = move || aceToFoundations(tableu, foundations);
        move = move || cardsToFoundation(tableu, foundations);
        move = move || kingToEmpty(tableu);
        move = move || lateralMoves(tableu);
        return move;

    }

    public static void main(String[] args) {
        // Initialize the stockpile
        ArrayList<Card> deck = new ArrayList<>();

        for (Suit suit : Suit.values()) {
            for (Value value : Value.values()) {
                deck.add(new Card(suit, value));
            }
        }

        Deque<Card> stock = new ArrayDeque<>();
        Deque<Card> waste = new ArrayDeque<>();

        Collections.shuffle(deck);
        for (Card card : deck) {
            stock.add(card);
        }

        // Initialize the tableu
        CardStack[] tableu = new CardStack[7];
        for (int i = 0; i < 7; i++) {
            tableu[i] = new CardStack(new LinkedList<Card>(), 0);
        }
        
        // Initialize the foundations
        Foundation[] foundations = new Foundation[4];
        for (int i = 0; i < 4; i++) {
            foundations[i] = new Foundation();
        }

        // Board gaming
    }
}
