/*
 * This source file was generated by the Gradle 'init' task
 */
package solitaire;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Deque;
import java.util.LinkedList;

import solitaire.utils.Card;
import solitaire.utils.CardStack;
import solitaire.utils.Foundation;
import solitaire.utils.Suit;
import solitaire.utils.Value;
import solitaire.utils.Waste;

public class App {
    public boolean wasteCardToTableu(Waste waste, Deque<Card> stock, CardStack[] tableu) {
        boolean move = false;
        if (waste.size() == 0) {
            waste.drawThreeFrom(stock);
        }

        Card top = waste.getTop();
        for (CardStack cardStack : tableu) {
            if (cardStack.empty()) {
                continue;
            }
            if (top.isCompatibleBelow(cardStack.getRevealedBottom())) {
                Card c = waste.popTop();

                cardStack.appendCard(c);
                move = true;
                break;
            }
        }
        return move;
    }

    public boolean wasteCardToFoundation(Waste waste, Deque<Card> stock, Foundation[] foundations) {
        boolean move = false;
        if (waste.size() == 0) {
            waste.drawThreeFrom(stock);
        }

        Card top = waste.getTop();

        for (Foundation foundation : foundations) {
            if (foundation.pushable(top)) {
                Card c = waste.popTop();
                foundation.push(c);
                move = true;
                break;
            }
        }

        return move;
    }

    public boolean wasteAceToFoundation(Waste waste, Deque<Card> stock, Foundation[] foundations) {
        boolean move = false;
        if (waste.size() == 0) {
            waste.drawThreeFrom(stock);
        }

        Card top = waste.getTop();
        if (top.value() != Value.ACE) {
            return false;
        }

        for (Foundation foundation : foundations) {
            if (!foundation.empty()) {
                continue;
            }

            Card c = waste.popTop();
            foundation.push(c);
            move = true;
            break;
        }

        return move;
    }

    public boolean wasteKingToTableu(Waste waste, Deque<Card> stock, CardStack[] tableu) {
        boolean move = false;
        if (waste.size() == 0) {
            waste.drawThreeFrom(stock);
        }

        Card top = waste.getTop();
        if (top.value() != Value.KING) {
            return false;
        }

        for (CardStack cardStack : tableu) {
            if (cardStack.empty()) {
                cardStack.pushCard(waste.popTop());
                move = true;
                break;
            }
        }

        return move;
    }

    public boolean cardsToFoundation(CardStack[] tableu, Foundation[] foundations) {
        boolean move = false;

        for (CardStack stack : tableu) {
            if (stack.empty()) {
                continue;
            }

            boolean pushable = true;
            while (!stack.empty() && pushable) {
                for (Foundation foundation : foundations) {
                    Card end = stack.getRevealedBottom();
                    if (!foundation.pushable(end)) {
                        pushable = false;
                        continue;
                    }

                    foundation.push(stack.popCard());
                    move = true;
                    pushable = true;
                    break;
                }
            }
        }

        return move;
    }

    public boolean aceToFoundations(CardStack[] tableu, Foundation[] foundations) {
        boolean move = false;
        for (CardStack stack : tableu) {
            if (stack.empty()) {
                continue;
            }
            Card end = stack.getRevealedBottom();
            if (end.value() != Value.ACE) {
                continue;
            }

            for (Foundation foundation : foundations) {
                if (!foundation.empty()) {
                    continue;
                }

                Card c = stack.popCard();
                foundation.push(c);
                move = true;
                break;
            }
        }

        return move;
    }

    public boolean kingToEmpty(CardStack[] tableu) {
        ArrayList<Integer> emptyStackIndexes = new ArrayList<>();
        boolean move = false;

        for (int i = 0; i < tableu.length; i++) {
            if (tableu[i].empty()) {
                emptyStackIndexes.add(i);
            }
        }
        // System.out.println(emptyStackIndexes.size());

        if(emptyStackIndexes.isEmpty()) {
            return move;
        }

        int nextMarkedStack = 0;

        for (CardStack stack : tableu) {
            if (stack.empty()) {
                continue;
            }

            if (nextMarkedStack >= emptyStackIndexes.size()) {
                break;
            }

            if (stack.revealedStart() > 0 && stack.getRevealedTop().value() == Value.KING) {
                CardStack kingStack = stack.splitStack(stack.revealedStart()).get();
                tableu[emptyStackIndexes.get(nextMarkedStack)].mergeStacks(kingStack);
                nextMarkedStack += 1;
                move = true;
            }
        }

        return move;
    }

    public boolean lateralMoves(CardStack[] tableu) {
        boolean move = false;

        // CardStack A - to move
        // CardStack B - to receive
        for (CardStack stackToMove : tableu) {
            if (stackToMove.empty()) {
                continue;
            }
            if (stackToMove.revealedStart() == 0 && stackToMove.getRevealedTop().value() == Value.KING) {
                continue;
            }
            for (CardStack stackToReceive : tableu) {
                if (stackToMove == stackToReceive) {
                    continue;
                }
                
                if (stackToReceive.empty()) {
                    continue;
                }

                if(stackToMove.getRevealedTop().isCompatibleBelow(stackToReceive.getRevealedBottom())) {
                    var temp = stackToMove.splitStack(stackToMove.revealedStart());

                    if(temp.isEmpty()) {
                        continue;
                    }

                    CardStack cs = temp.get();

                    stackToReceive.mergeStacks(cs);
                    move = true;
                    break;
                }
            }
        }

        return move;
    }

    public boolean buildTableu(CardStack[] tableu, Foundation[] foundations) {
        boolean move = false;
        move = move || aceToFoundations(tableu, foundations);
        move = move || cardsToFoundation(tableu, foundations);
        move = move || kingToEmpty(tableu);
        move = move || lateralMoves(tableu);
        return move;
    }

    public boolean playOneCycle(CardStack[] tableu, Foundation[] foundations, Waste waste, Deque<Card> stock) {
        while (buildTableu(tableu, foundations)) {}
        boolean moveMade = false;
        while (!stock.isEmpty()) {
            waste.drawThreeFrom(stock);
            boolean wasteMove = this.wasteAceToFoundation(waste, stock, foundations);
            wasteMove = this.wasteCardToFoundation(waste, stock, foundations);
            wasteMove = this.wasteKingToTableu(waste, stock, tableu);
            wasteMove = this.wasteCardToTableu(waste, stock, tableu);
            if (!wasteMove) {
            } else {
                moveMade = true;
                while (buildTableu(tableu, foundations)) {}
            }
        }
        waste.refresh(stock);
        return moveMade;
    }

    // Target
/*
S -- 0(D)		                5(H)  3(D)  4(C)  --

----  -(-)  -(-)  -(-)  -(-)  -(-)  ----  ----  ----
      -(-)  -(-)  -(-)  -(-)  -(-)
      1(H)  -(-)  -(-)  -(-)  5(C)
	  -(-)	1(C)  4(S) 
	  -(-)
	  K(D)
*/
    public void displayTableu(CardStack[] tableu) {
        for (CardStack cardStack : tableu) {
            cardStack.display();
        }
    }

    public CardStack[] initializeTableu(ArrayList<Card> deck) {
        CardStack[] tableu = new CardStack[7];
        for (int i = 0; i < 7; i++) {
            tableu[i] = new CardStack(new LinkedList<Card>(), i);
            for (int j = 0; j < i+1; j++) {
                Card c = deck.remove(0);
                tableu[i].appendCard(c);
            }
        }

        return tableu;
    }

    public Deque<Card> initializeStock(ArrayList<Card> deck) {
        Deque<Card> stock = new ArrayDeque<>();

        while (!deck.isEmpty()) {
            Card c = deck.remove(0);
            stock.add(c);
        }
        
        return stock;
    }

    public void displayState(CardStack[] tableu, Deque<Card> stock, Foundation[] foundations, Waste waste) {
        Card topStock = stock.peek();

        System.out.print("S--" + topStock.toDisplayString());
        for (int i = 0; i < 16; i++) {
            System.out.print(" ");
        }

        for (Foundation foundation : foundations) {
            if (foundation.empty()) {
                System.out.print("----  ");
                continue;
            }

            System.out.print(foundation.getTop().toDisplayString() + "  ");
            if (foundation.getTop().value() != Value.TEN) {
                System.out.print(" ");
            }
        }

        System.out.println();
        System.out.println();

        int maxSizeStack = 0;
        for (CardStack stack : tableu) {
            if (stack.size() > maxSizeStack) {
                maxSizeStack = stack.size();
            }
        }
        for (int i = 0; i < maxSizeStack; i++) {
            for (CardStack stack : tableu) {
                if (i >= stack.size()) {
                    System.out.print("       ");
                    // System.out.print("----   ");
                    continue;
                }

                if (i < stack.revealedStart()) {
                    System.out.print("-(-)   ");
                    continue;
                }

                System.out.print(stack.getCard(i).toDisplayString());
                System.out.print("  ");
                if (stack.getCard(i).value() != Value.TEN) {
                    System.out.print(" ");
                }
            }
            System.out.println();
        }
    }

    public static void main(String[] args) {
        // Initialize the stockpile
        ArrayList<Card> deck = new ArrayList<>();

        for (Suit suit : Suit.values()) {
            for (Value value : Value.values()) {
                deck.add(new Card(suit, value));
            }
        }

        Collections.shuffle(deck);
        System.out.println("Printing Deck Order");
        for (Card card : deck) {
            System.out.println(card.toDisplayString());
        }

        App app = new App();
        // Initialize the tableu
        CardStack[] tableu = app.initializeTableu(deck);

        Deque<Card> stock = app.initializeStock(deck);
        Waste waste = new Waste();
        
        // Initialize the foundations
        Foundation[] foundations = new Foundation[4];
        for (int i = 0; i < 4; i++) {
            foundations[i] = new Foundation();
        }

        // Board gaming
        boolean move = true;
        boolean win = false;
        while (move && win == false) {
            move = app.playOneCycle(tableu, foundations, waste, stock);
            System.out.println("");
            app.displayState(tableu, stock, foundations, waste);
            System.out.println("");
            for (Foundation foundation : foundations) {
                boolean complete = true;
                if (foundation.size() < 13) {
                    complete = false;
                    break;
                }

                win = complete;
            }
        }

        if (win) {
            System.out.println("You win!");
        } else {
            System.out.println("You lost!");
        }

        app.displayState(tableu, stock, foundations, waste);
    }
}
