/*
 * This source file was generated by the Gradle 'init' task
 */
package solitaire;

import java.util.Scanner;

import solitaire.utils.BoardDisplay;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        Game game = new Game();

        BoardDisplay display = BoardDisplay.withBoard(game);
        display.setScanner(scanner);
        
        System.out.println("Starting the game GLHF");
        display.displayState();

        boolean win = game.play();

        if (win) {
            System.out.println("You win!");
        } else {
            System.out.println("You lost!");
        }

        scanner.close();
    }
}
